services:
  # Backend API Server
  - type: web
    name: daveenci-ai-backend
    env: node
    plan: starter  # Changed from free to starter for cron support
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main
    rootDir: /
    scaling:
      minInstances: 1
      maxInstances: 1

  # Frontend Web Service (Node.js serving static files)
  - type: web
    name: daveenci-ai-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build && cp frontend-package.json package.json && npm install
    startCommand: node frontend-server.js
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main
    rootDir: /
    scaling:
      minInstances: 1
      maxInstances: 1

  # Blog Automation Cron Service - Test at 5:00 PM CDT (22:00 UTC)
  - type: cron
    name: daveenci-blog-automation
    env: node
    plan: starter
    buildCommand: cd server && npm install
    # Test schedule: Every 10 minutes for testing
    schedule: "*/10 * * * *"  # Every 10 minutes for testing - will switch to production schedule once confirmed working
    startCommand: cd server && node automation/blog-scheduler.js auto
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main
    rootDir: / 