services:
  # Backend API Server
  - type: web
    name: daveenci-ai-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    branch: main
    rootDir: /
    scaling:
      minInstances: 1
      maxInstances: 1

  # Frontend Static Site
  - type: static
    name: daveenci-ai-website
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
    branch: main
    rootDir: / 